name: portfolio-tws

on: 
  push:
    branches:
    - main 
jobs:
    deploy:
      runs-on: ubuntu:latest
      steps:
      - name: git checkout
        uses: actions/checkout@v1

      - name: configure-aws
        uses: aws-actions/configure-aws-credentials
        with: 
          aws-access-key-id: 
          
    
     
  
    
